version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: my_mysql_db_asp_dotnet
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: onlinestoredb
      MYSQL_USER: storeuser
      MYSQL_PASSWORD: storeuserpass
    ports:
      - "3306:3306"
    volumes:
      - asp_dotnet_project:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - onlinestore-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onlinestore_app
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=onlinestoredb;User=storeuser;Password=storeuserpass;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - onlinestore-network

volumes:
  asp_dotnet_project:
    driver: local

networks:
  onlinestore-network:
    driver: bridge
